export default {
    welcomeUser: (name) => `Welcome, ${name}!`,
    welcomeBack: 'Welcome Back',
    signIn: 'Sign in to continue to FairShare',
    email: 'Email',
    emailReq: 'Email is required',
    passwordReq: 'Password is required',
    password: 'Password',
    register: 'Register',
    dontHaveAcc: 'Don\'t have an account?',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    createAcc: 'Create Account',
    joinSplittr: 'Join Splittr today',
    fullName: 'Full Name',
    alreadyAcc: 'Already have an account?',
    creatingAcc: 'Creating Account...',
    signUp: 'Sign Up',
    yourGroups: 'Your Groups',
    createGroup: 'Create Group',
    noGroups: 'You are not part of any groups yet.',
    createAgrp: 'Create a group to start splitting expenses with friends.',
    members: 'members', 
    createNewGrp: 'Create New Group',
    groupNamePlaceholder: 'Group Name (e.g. Apartment Expenses)',
    cancel: 'Cancel',
    create: 'Create',
    failedGrps: 'Failed to load groups',
    settlr: 'Settlr',
    dashboard: 'Dashboard',
    groups: 'Groups',
    subscriptions: 'Subscriptions',
    activity: 'Activity',
    creating: 'Creating...',
    manageGroups: 'Manage Groups',
    addExpense: 'Add Expense',
    noExpenses: 'No expenses yet. Add one to get started!',
     

}